version: '3'
services:
  # 服务名称
  nginx:
    # 镜像:版本
    image: registry.njuics.cn/typhoon-frontend/typhoon-frontend:latest
    container_name: typhoon-frontend
    # 映射容器80端口到本地80端口
    ports:
     - "80:80"
    # 数据卷 映射本地文件到容器
    # volumes:
    #  - ./nginx/conf:/etc/nginx/conf.d
    # # # 映射build文件夹到容器的/usr/share/nginx/html文件夹
    #  - ./nginx/www:/usr/share/nginx/html
    #  - ./nginx/logs:/var/log/nginx
    # # 覆盖容器启动后默认执行的命令。
    command: /bin/bash -c "nginx -g 'daemon off;'"